#version: '3.8'

services:
  debtservice:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "5039:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080 
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=debtdb;User=userMysql;Password=Debt123;
    depends_on:
      - mysql
    networks:
      - backend

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: debtdb
      MYSQL_USER: userMysql
      MYSQL_PASSWORD: Debt123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mysql_data: